// <auto-generated />
using System;
using DoxFlorisMVCWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoxFlorisMVCWeb.Migrations
{
    [DbContext(typeof(DoxFlorisMVCWebContext))]
    [Migration("20190528071046_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoxFlorisMVCWeb.Models.Bericht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("datum");

                    b.Property<string>("inhoud");

                    b.Property<int>("lidId");

                    b.Property<string>("titel");

                    b.HasKey("Id");

                    b.HasIndex("lidId");

                    b.ToTable("Bericht");
                });

            modelBuilder.Entity("DoxFlorisMVCWeb.Models.Lid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("achternaam");

                    b.Property<string>("email");

                    b.Property<DateTime>("geboortedatum");

                    b.Property<string>("huisnummer");

                    b.Property<string>("land");

                    b.Property<string>("postcode");

                    b.Property<string>("straat");

                    b.Property<string>("telefoon");

                    b.Property<string>("voornaam");

                    b.HasKey("Id");

                    b.ToTable("Lid");
                });

            modelBuilder.Entity("DoxFlorisMVCWeb.Models.Speedrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("datum");

                    b.Property<int>("lidId");

                    b.Property<string>("plank");

                    b.Property<double>("snelheid");

                    b.Property<string>("zeil");

                    b.HasKey("Id");

                    b.HasIndex("lidId");

                    b.ToTable("Speedrun");
                });

            modelBuilder.Entity("DoxFlorisMVCWeb.Models.Bericht", b =>
                {
                    b.HasOne("DoxFlorisMVCWeb.Models.Lid", "lid")
                        .WithMany("berichten")
                        .HasForeignKey("lidId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DoxFlorisMVCWeb.Models.Speedrun", b =>
                {
                    b.HasOne("DoxFlorisMVCWeb.Models.Lid", "lid")
                        .WithMany("speedruns")
                        .HasForeignKey("lidId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
